package a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CAFE".
*/
public class cafeDao extends AbstractDao<cafe, Long> {

    public static final String TABLENAME = "CAFE";

    /**
     * Properties of entity cafe.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CafeName = new Property(1, String.class, "cafeName", false, "CAFE_NAME");
        public final static Property CafeAddress = new Property(2, String.class, "cafeAddress", false, "CAFE_ADDRESS");
        public final static Property Latitude = new Property(3, long.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(4, long.class, "longitude", false, "LONGITUDE");
    }


    public cafeDao(DaoConfig config) {
        super(config);
    }
    
    public cafeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CAFE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"CAFE_NAME\" TEXT NOT NULL ," + // 1: cafeName
                "\"CAFE_ADDRESS\" TEXT NOT NULL ," + // 2: cafeAddress
                "\"LATITUDE\" INTEGER NOT NULL ," + // 3: latitude
                "\"LONGITUDE\" INTEGER NOT NULL );"); // 4: longitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CAFE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, cafe entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCafeName());
        stmt.bindString(3, entity.getCafeAddress());
        stmt.bindLong(4, entity.getLatitude());
        stmt.bindLong(5, entity.getLongitude());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, cafe entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getCafeName());
        stmt.bindString(3, entity.getCafeAddress());
        stmt.bindLong(4, entity.getLatitude());
        stmt.bindLong(5, entity.getLongitude());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public cafe readEntity(Cursor cursor, int offset) {
        cafe entity = new cafe( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // cafeName
            cursor.getString(offset + 2), // cafeAddress
            cursor.getLong(offset + 3), // latitude
            cursor.getLong(offset + 4) // longitude
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, cafe entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCafeName(cursor.getString(offset + 1));
        entity.setCafeAddress(cursor.getString(offset + 2));
        entity.setLatitude(cursor.getLong(offset + 3));
        entity.setLongitude(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(cafe entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(cafe entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(cafe entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
