package a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CAFE".
 */
@Entity
public class cafe {

    @Id
    private Long id;

    @NotNull
    private String cafeName;

    @NotNull
    private String cafeAddress;
    private long latitude;
    private long longitude;

    @Generated
    public cafe() {
    }

    public cafe(Long id) {
        this.id = id;
    }

    @Generated
    public cafe(Long id, String cafeName, String cafeAddress, long latitude, long longitude) {
        this.id = id;
        this.cafeName = cafeName;
        this.cafeAddress = cafeAddress;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCafeName() {
        return cafeName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCafeName(@NotNull String cafeName) {
        this.cafeName = cafeName;
    }

    @NotNull
    public String getCafeAddress() {
        return cafeAddress;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCafeAddress(@NotNull String cafeAddress) {
        this.cafeAddress = cafeAddress;
    }

    public long getLatitude() {
        return latitude;
    }

    public void setLatitude(long latitude) {
        this.latitude = latitude;
    }

    public long getLongitude() {
        return longitude;
    }

    public void setLongitude(long longitude) {
        this.longitude = longitude;
    }

}
