package a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema.cafe;

import a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema.cafeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cafeDaoConfig;

    private final cafeDao cafeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cafeDaoConfig = daoConfigMap.get(cafeDao.class).clone();
        cafeDaoConfig.initIdentityScope(type);

        cafeDao = new cafeDao(cafeDaoConfig, this);

        registerDao(cafe.class, cafeDao);
    }
    
    public void clear() {
        cafeDaoConfig.clearIdentityScope();
    }

    public cafeDao getCafeDao() {
        return cafeDao;
    }

}
