package a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema.Category;
import a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema.Locations;

import a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema.CategoryDao;
import a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema.LocationsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig locationsDaoConfig;

    private final CategoryDao categoryDao;
    private final LocationsDao locationsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(CategoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        locationsDaoConfig = daoConfigMap.get(LocationsDao.class).clone();
        locationsDaoConfig.initIdentityScope(type);

        categoryDao = new CategoryDao(categoryDaoConfig, this);
        locationsDao = new LocationsDao(locationsDaoConfig, this);

        registerDao(Category.class, categoryDao);
        registerDao(Locations.class, locationsDao);
    }
    
    public void clear() {
        categoryDaoConfig.clearIdentityScope();
        locationsDaoConfig.clearIdentityScope();
    }

    public CategoryDao getCategoryDao() {
        return categoryDao;
    }

    public LocationsDao getLocationsDao() {
        return locationsDao;
    }

}
