package a00971903.comp3717.ca.bcit.ca.explorenewwest.database.schema;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOCATIONS".
*/
public class LocationsDao extends AbstractDao<Locations, Long> {

    public static final String TABLENAME = "LOCATIONS";

    /**
     * Properties of entity Locations.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Latitude = new Property(2, long.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(3, long.class, "longitude", false, "LONGITUDE");
        public final static Property CategoryID = new Property(4, long.class, "categoryID", false, "CATEGORY_ID");
    }


    public LocationsDao(DaoConfig config) {
        super(config);
    }
    
    public LocationsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOCATIONS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"LATITUDE\" INTEGER NOT NULL ," + // 2: latitude
                "\"LONGITUDE\" INTEGER NOT NULL ," + // 3: longitude
                "\"CATEGORY_ID\" INTEGER NOT NULL );"); // 4: categoryID
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOCATIONS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Locations entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getLatitude());
        stmt.bindLong(4, entity.getLongitude());
        stmt.bindLong(5, entity.getCategoryID());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Locations entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getLatitude());
        stmt.bindLong(4, entity.getLongitude());
        stmt.bindLong(5, entity.getCategoryID());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Locations readEntity(Cursor cursor, int offset) {
        Locations entity = new Locations( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getLong(offset + 2), // latitude
            cursor.getLong(offset + 3), // longitude
            cursor.getLong(offset + 4) // categoryID
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Locations entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setLatitude(cursor.getLong(offset + 2));
        entity.setLongitude(cursor.getLong(offset + 3));
        entity.setCategoryID(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Locations entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Locations entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Locations entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
